spring:
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-nodes: 119.8.108.5:9300
      cluster-name: my-application
  #sentinel控制框架
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: src/main/resources
  zipkin:
    enabled: true
    base-url: http://127.0.0.1:9411/
    # discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    #   数据源基本配置
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/yuekeju?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
  #   数据源其他配置
  druid:
    #     配置初始化大小、最小、最大线程数
    initialSize: 5
    minIdle: 5
    #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
    maxActive: 20
    #     最大等待时间，内网：800，外网：1200（三次握手1s）
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    #     配置一个连接在池中最大空间时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    #     设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
    testOnBorrow: true
    #     设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
    testOnReturn: true
    #     可以支持PSCache（提升写入、查询效率）
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    #     保持长连接
    keepAlive: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    database: 0
    host: 192.168.99.100
    port: 6379
    password:

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace:
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace:
      application: seata-server
  service:
    vgroup-mapping:
      my_test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false

oos:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  keyid: LTAI9aJru3bCIPPY # 填写刚刚生成的AccessKey
  keysecret: BcY3We9JpVLb0yUU7cRZnmkUdfUnhs  # 填写刚刚生成的Accesssecret
  bucketname: yuekeju # bucket名称
  filehost: file    #bucket下文件夹的路径
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error