spring:
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-nodes: 119.8.108.5:9300
      cluster-name: my-application
  #sentinel控制框架
  cloud:
    sentinel:
      transport:
        dashboard: 119.8.108.5:8080
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: src/main/resources
  zipkin:
    enabled: true
    base-url: http://119.8.108.5:9411/
    # discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0
oos:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  keyid: LTAI9aJru3bCIPPY # 填写刚刚生成的AccessKey
  keysecret: BcY3We9JpVLb0yUU7cRZnmkUdfUnhs  # 填写刚刚生成的Accesssecret
  bucketname: yuekeju # bucket名称
  filehost: file    #bucket下文件夹的路径
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error